apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odp-prod
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: patch-configmap.yaml
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
  - path: patch-storage.yaml
  - path: patch-ingress.yaml
  - path: patch-hpa.yaml
  - path: patch-pdb.yaml
