apiVersion: batch/v1
kind: Job
metadata:
  name: datahub-elasticsearch-setup
  namespace: odp-dev
  labels:
    app.kubernetes.io/name: datahub-elasticsearch-setup
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datahub-elasticsearch-setup
    spec:
      restartPolicy: OnFailure
      containers:
        - name: datahub-elasticsearch-setup
          image: acryldata/datahub-elasticsearch-setup:v1.2.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_HOST
              value: datahub-elasticsearch
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_PROTOCOL
              value: http
