apiVersion: batch/v1
kind: Job
metadata:
  name: datahub-mysql-setup
  namespace: odp-dev
  labels:
    app.kubernetes.io/name: datahub-mysql-setup
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datahub-mysql-setup
    spec:
      restartPolicy: OnFailure
      containers:
        - name: datahub-mysql-setup
          image: acryldata/datahub-mysql-setup:v1.2.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOST
              value: datahub-mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odp-env
                  key: DATAHUB_MYSQL_ROOT_PASSWORD
            - name: DATAHUB_DB_NAME
              value: datahub
