apiVersion: batch/v1
kind: Job
metadata:
  name: datahub-upgrade
  namespace: odp-dev
  labels:
    app.kubernetes.io/name: datahub-upgrade
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datahub-upgrade
    spec:
      restartPolicy: OnFailure
      containers:
        - name: datahub-upgrade
          image: acryldata/datahub-upgrade:v1.2.0.1
          imagePullPolicy: IfNotPresent
          args:
            - -u
            - SystemUpdate
          env:
            - name: EBEAN_DATASOURCE_USERNAME
              value: root
            - name: EBEAN_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odp-env
                  key: DATAHUB_MYSQL_ROOT_PASSWORD
            - name: EBEAN_DATASOURCE_HOST
              value: datahub-mysql:3306
            - name: EBEAN_DATASOURCE_URL
              value: jdbc:mysql://datahub-mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
            - name: EBEAN_DATASOURCE_DRIVER
              value: com.mysql.jdbc.Driver
            - name: KAFKA_BOOTSTRAP_SERVER
              value: datahub-kafka:29092
            - name: KAFKA_SCHEMAREGISTRY_URL
              value: http://datahub-schema-registry:8081
            - name: ELASTICSEARCH_HOST
              value: datahub-elasticsearch
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: GRAPH_SERVICE_IMPL
              value: elasticsearch
            - name: ENTITY_REGISTRY_CONFIG_PATH
              value: /datahub/datahub-gms/resources/entity-registry.yml
            - name: DATAHUB_GMS_HOST
              value: datahub-gms
            - name: DATAHUB_GMS_PORT
              value: "8080"
