apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-airflow.yaml
  - warehouse.yaml
  - keycloak.yaml
  - minio.yaml
  - minio-create-buckets-job.yaml
  - airflow-init-job.yaml
  - airflow-webserver.yaml
  - airflow-scheduler.yaml
