apiVersion: v1
kind: Namespace
metadata:
  name: odp-dev
  labels:
    app.kubernetes.io/name: open-data-platform
    app.kubernetes.io/environment: dev
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
