apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - eu-sovereigndataplatform.com
        - www.eu-sovereigndataplatform.com
        - airflow.eu-sovereigndataplatform.com
        - minio.eu-sovereigndataplatform.com
        - minio-api.eu-sovereigndataplatform.com
      secretName: frontend-tls
  rules:
    - host: eu-sovereigndataplatform.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: www.eu-sovereigndataplatform.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: airflow.eu-sovereigndataplatform.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airflow-webserver
                port:
                  number: 8080
    - host: minio.eu-sovereigndataplatform.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
    - host: minio-api.eu-sovereigndataplatform.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
