apiVersion: v1
kind: ConfigMap
metadata:
  name: odp-runtime
data:
  ENVIRONMENT: dev
  OTEL_SERVICE_NAMESPACE: open-data-platform-dev
  AIRFLOW_WEBSERVER_BASE_URL: https://airflow.eu-sovereigndataplatform.com
