apiVersion: v1
kind: ConfigMap
metadata:
  name: odp-runtime
data:
  ENVIRONMENT: staging
  OTEL_SERVICE_NAMESPACE: open-data-platform-staging
  AIRFLOW_WEBSERVER_BASE_URL: https://airflow.staging.example.com
