apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccounts.yaml
  - rbac.yaml
  - configmap-runtime.yaml
  - postgres.yaml
  - warehouse.yaml
  - minio.yaml
  - minio-create-buckets-job.yaml
  - airflow-init-job.yaml
  - airflow-webserver.yaml
  - airflow-scheduler.yaml
  - frontend.yaml
  - ingress.yaml
  - pdb.yaml
  - hpa.yaml
  - networkpolicies.yaml
