apiVersion: v1
kind: Secret
metadata:
  name: odp-env
type: Opaque
stringData:
  AIRFLOW_DB_USER: "<set-me>"
  AIRFLOW_DB_PASSWORD: "<set-me>"
  AIRFLOW_DB_NAME: "airflow"
  AIRFLOW_FERNET_KEY: "<set-me-32-byte-urlsafe-base64>"
  AIRFLOW_ADMIN_USER: "admin"
  AIRFLOW_ADMIN_PASSWORD: "<set-me>"
  AIRFLOW_ADMIN_EMAIL: "admin@example.com"

  MINIO_ROOT_USER: "<set-me>"
  MINIO_ROOT_PASSWORD: "<set-me-min-8-chars>"

  WAREHOUSE_DB: "open_data_platform_dw"
  WAREHOUSE_USER: "<set-me>"
  WAREHOUSE_PASSWORD: "<set-me>"

  KEYCLOAK_AIRFLOW_CLIENT_ID: "airflow"
  KEYCLOAK_AIRFLOW_CLIENT_SECRET: "<set-me>"
  KEYCLOAK_MINIO_CLIENT_ID: "minio"
  KEYCLOAK_MINIO_CLIENT_SECRET: "<set-me>"
  KEYCLOAK_OIDC_BASE_URL: "<optional>"
  KEYCLOAK_OIDC_AUTHORIZE_URL: "<optional>"
  KEYCLOAK_OIDC_TOKEN_URL: "<optional>"
  KEYCLOAK_OIDC_DISCOVERY_URL: "<optional>"

  AIRFLOW_OAUTH_DEFAULT_ROLE: "Admin"
  MINIO_OIDC_REDIRECT_URI: "<optional>"
  MINIO_BROWSER_REDIRECT_URL: "<optional>"
  MINIO_SERVER_URL: "<optional>"
