apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-webserver
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-scheduler
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-init
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: warehouse
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-bootstrap
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
automountServiceAccountToken: false
