global:
  resolve_timeout: 5m

route:
  receiver: teams
  group_by: [alertname, job]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: teams
    webhook_configs:
      - url: http://prometheus-msteams:2000/alertmanager
        send_resolved: true
