global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: alertmanager
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: statsd-exporter
    static_configs:
      - targets: ["statsd-exporter:9102"]

  - job_name: postgres-airflow
    static_configs:
      - targets: ["postgres-exporter-airflow:9187"]

  - job_name: postgres-warehouse
    static_configs:
      - targets: ["postgres-exporter-warehouse:9187"]

  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]
